### PR TITLE
Fix errors on INSERTs

### PR DESCRIPTION
**Pull request by jdelStrother**
This fixes `undefined method 'reverse' for nil:NilClass` (#27), along with a couple of other errors related to handling of INSERT/UPDATE statements.  WDYT?

### CODE REVIEW

**Comment by nesquena** [comment]
Would these changes mean that query_reviewer only works with Rails 4?

**Comment by nesquena** [comment]
@jdelStrother If it does which I suspect is the case, then perhaps I should just bump the version and have Rails 4 people use latest and everyone else use older version?

**Comment by jdelStrother** [comment]
I'm using it with Rails 3.2.6, I haven't actually tested it with other
versions. I suppose I ought to give it a go with Rails 4 at least...

**Comment by nesquena** [comment]
If you (or someone) can verify it works with Rails 4, then I'll pull this in and release a new version.

**Comment by jdelStrother** [comment]
Will do.   By the way - I don't know where I got 3.2.6 from, I've actually been testing it on 3.2.14.  Think it's sufficient to just try on the latest 3.2 & on Rails 4?

**Comment by nesquena** [comment]
Yeah I think if it works on those two, then I am ready to ship the update. Thanks!

**Comment by jdelStrother** [comment]
Yep, seems fine to me in Rails 3.2.14 and in my tiny Rails 4 test app.

**Comment by nesquena** [comment]
Released version 0.2.0. Thanks!

**Comment by noahsw** [comment]
Works great!

**Comment by noahsw** [comment]
0.2.0 resolved my issues with rails_admin but now I'm seeing these same errors in my own app. I can't seem to figure out any pattern as to why my particular `.create!` statement causes this and not others. Baffling...

Anyone else still having issues?

**Pull request merged**
