### PR TITLE
Rails 3.1+ support

### PR DESCRIPTION
**Pull request by vnorby**
QueryReviewer doesn't work in Rails 3.1+, I think because silence was deprecated. I changed it to quietly which fixes the issue for me.

### CODE REVIEW

**Comment by nesquena** [comment]
Looks like this was introduced on Rails 3.1. If I were to pull in this change wouldn't it break compatibility completely with < 3.1?

**Comment by nesquena** [comment]
Thanks that looks like it will work.

**Comment by nesquena** [comment]
Pushed a new release, thanks

**Comment by vnorby** [comment]
Thanks Nathan, appreciate your work on this.

**Pull request merged**
